name: publish

on:
  push:
    branches:
      - master

jobs:
  publish-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: create keys
        run: |
          mkdir -p ~/.ssh
          echo '${{secrets.PRIVATE_KEY}}' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 1.2.3.4 >> ~/.ssh/known_hosts
          ls -l -a ~/.ssh
      - name: install hexo-cli
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i -g hexo-cli

      - name: install hexo dependencies
        run: npm i
        working-directory: hexo

      - name: pull themes
        run: |
          mkdir -p hexo/themes
          git clone -b master https://github.com/jerryc127/hexo-theme-butterfly.git hexo/themes/butterfly
          echo 'themes config'
          cp hexo/themes_butterfly_config.yml hexo/themes/butterfly/_config.yml
          echo 'background image'
          cp hexo/images/bg.png hexo/themes/butterfly/source/img/bg.png
      - name: install themes package
        run: npm i
        working-directory: hexo/themes/butterfly

      - name: check themes package
        run: ls -l
        working-directory: hexo/themes/butterfly

      - name: git config
        run: |
          git config --global user.name imba97
          git config --global user.email mail@imba97.cn
          git config --global init.defaultBranch master
        working-directory: hexo

      - name: hexo generate
        run: |
          hexo clean
          hexo g
        working-directory: hexo

      - name: deploy!
        run: |
          git init
          git add .
          git commit -m "deploy!"
          git remote add origin root@1.2.3.4:/git/blog.git
          git push --force origin master
        working-directory: hexo/public
